[AOC_mini]
MiniImageWidth=100
MaxImageWidth=100
;1患者の場合aoc_miniのリストを開かずビューアーを表示する
OpenViewerIfPatientCountIsOne=0
;1検査の場合aoc_miniのリストを開かずビューアーを表示する
OpenViewerIfImagesetCountIsOne=0

ShowImageCount=1

#患者IDを表示する設定
#ShowPatientIdInList=1 
#Accsession Numberをリストに表示 
#ShowAccNum=1

[Viewer]
InterfaceVersion=5